apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: prod-net
  annotations:
    platform.io/resource-type: network
spec:
  type: network
  owner: "group:default/payments"
  definition:
    apiVersion: platform/v1
    kind: Network
    metadata:
      name: prod-net
      ownerTeam: payments
    spec:
      cidr: 10.0.0.0/16
      region: eu-west-1
    payload:
      method: POST
      url: "https://net.api/networks"
      body:
        name: prod-net
        cidr: 10.0.0.0/16
        region: eu-west-1
    mapping:
      children: {}
      internals: {}
