apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: admin
spec:
  memberOf:
    - platform-admins
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: requester
spec:
  memberOf:
    - owners-payments
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: auditor
spec:
  memberOf:
    - platform-auditors
