#!/usr/bin/env bash
# Bring up the self-contained Backstage stack: docker services (Postgres,
# Keycloak, Gitea, OpenLDAP), seed Gitea repos, and a kind + Argo cluster.
# Coexists with the legacy stack (distinct ports). Then start Backstage with:
#   cd backstage && yarn start
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
COMPOSE="docker compose -p backstage -f deploy/dev/docker-compose.yml"

# ---------------------------------------------------------------- dev secrets
# The two credentials that are dangerous to commit — a static backend bearer
# token and the session-signing secret — are generated here into
# app-config.local.yaml, which is gitignored.
#
# Written only when that file does not exist. Appending to one that does would
# duplicate top-level keys (`backend:`, `auth:`, `proxy:`), and YAML rejects a
# duplicate key outright: the app then fails to start with a parse error rather
# than doing anything useful. If you already have a local config, the snippet is
# printed for you to merge by hand.
LOCAL_CONFIG="backstage/app-config.local.yaml"
if ! grep -q "local-smoke" "$LOCAL_CONFIG" 2>/dev/null; then
  gen() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48; }
  SMOKE_TOKEN="$(gen)"
  SESSION_SECRET="$(gen)"
  SNIPPET="$(cat <<EOF
backend:
  auth:
    externalAccess:
      - type: static
        options:
          token: ${SMOKE_TOKEN}
          subject: local-smoke
auth:
  session:
    secret: ${SESSION_SECRET}
# The demo proxy calls our own /options endpoint, which requires that same
# token — kept together so the two can never disagree.
proxy:
  endpoints:
    '/demo-options':
      headers:
        Authorization: Bearer ${SMOKE_TOKEN}
EOF
)"
  if [ -s "$LOCAL_CONFIG" ]; then
    echo "==> [0/3] $LOCAL_CONFIG already exists — merge this in by hand:"
    echo ""
    echo "$SNIPPET" | sed 's/^/    /'
    echo ""
    echo "    (merge into the existing keys; do not append, YAML forbids duplicates)"
  else
    echo "==> [0/3] generating local dev secrets ($LOCAL_CONFIG)"
    {
      echo "# Generated by scripts/backstage-up.sh. Gitignored, local to this machine."
      echo "# Delete this file and re-run the script to rotate."
      echo "$SNIPPET"
    } > "$LOCAL_CONFIG"
    echo "    written"
  fi
fi


echo "==> [1/3] docker services (postgres:5433, keycloak:8081, gitea:3001, ldap:1389)"
$COMPOSE up -d

echo "==> waiting for Keycloak realm 'platform' (http://localhost:8081)"
for i in $(seq 1 90); do
  curl -sf http://localhost:8081/realms/platform >/dev/null 2>&1 && { echo "    Keycloak ready"; break; }
  [ "$i" -eq 90 ] && { echo "Keycloak did not become ready" >&2; exit 1; }
  sleep 2
done

echo "==> waiting for Gitea (http://localhost:3001)"
for i in $(seq 1 60); do
  curl -sf http://localhost:3001/api/v1/version >/dev/null 2>&1 && { echo "    Gitea ready"; break; }
  [ "$i" -eq 60 ] && { echo "Gitea did not become ready" >&2; exit 1; }
  sleep 2
done

echo "==> [2/3] seed Gitea repos"
bash deploy/dev/gitea-seed.sh

echo "==> [3/3] kind cluster + Argo Workflows"
bash deploy/dev/kind-argo-up.sh

cat <<'EOF'

  Stack ready. Now start Backstage:
    cd backstage && yarn start

  URLs:
    Backstage   http://localhost:3000   (backend :7007)
    Keycloak    http://localhost:8081    (admin/admin)
    Gitea       http://localhost:3001    (platform/platform)
    argo-server http://localhost:2746
EOF
